### ISSUE TITLE
Module not found: Error: Default condition should be last one

### ISSUE THREAD

**Issue by Vuizur** [denostack/superserial#2]
Hello,

thanks for creating this project! 

With the standard install, I encountered this error, but managed to resolve it like described in this comment: https://github.com/mpociot/chatgpt-vscode/issues/1#issuecomment-1337384976

(I don't know how the affected file is created though)

**Comment by wan2land** [comment]
Did you import and use it as follows?

```javascript
import superserial from 'superserial'
```

This package does not provide default exports. You must explicitly use the class you want to use.

```
import { Serializer } from 'superserial'
```

You can use an autocomplete class or type like this:

![](https://user-images.githubusercontent.com/4086535/208715867-c9d97a44-e6fa-45da-a88c-685b5eab255e.png)

If this doesn't work, please tell me in detail about the version of yarn or npm and how you reproduced it. thank you :smile:

**Comment by Vuizur** [comment]
Thank you very much for the reply. 😀

I used it like this:
```typescript
import { Serializer } from 'superserial'
```
My data: Windows, npm 9.2.0

At first I assumed it could be fixed by doing the same thing as done here: https://github.com/transitive-bullshit/chatgpt-api/commit/343157c2669be93cacea88209641518da792b884

But then I couldn't find a package.json in your repo, so now I have no idea.

**Comment by wan2land** [comment]
I finally found it. 😄  It was a problem that only happened in the webpack environment.

https://github.com/webpack/enhanced-resolve/blob/main/lib/util/entrypoints.js#L455

Referring to the package.json document, it is recommended to use the default item last.

https://nodejs.org/api/packages.html

I am using a package.json file created through a library called `dnt`. Fortunately, the related bug was fixed a week ago.

https://github.com/denoland/dnt/releases/tag/0.32.1

It will be redeployed after rebuilding.

**Comment by wan2land** [comment]
try v0.3.3 :smile:

**Comment by Vuizur** [comment]
Awesome, thanks 👍

пн, 26 дек. 2022 г., 01:23 Changwan Jun ***@***.***>:
