### ISSUE TITLE
Complex Objects

### ISSUE THREAD

**Issue by elarrat** [denostack/superserial#7]
I tried to serialize/deserialize a `@google-cloud/pubsub` Topic class object and the library presented some unexpected behaviors.

When I tried to serialize, I had to change `serialize.js`, line 113 to:
```
        const name = value.constructor && value.constructor !== Object && value.constructor !== Function
            ? value.constructor.name
            : "";
```
This additional `value.constructor` check made sure that empty objects pass this validation.

And when I deserialize it, I get the error in `deserialize.js`, line 58: `TypeError: Cannot read properties of undefined (reading 'projectId')`. This one has been a little more trick to figure out and I haven't yet, maybe when you have some time to spare I'd very appreciate your support.

Awesome lib by the way, congratz on the great job!

**Comment by wan2land** [comment]
`serialize` is presumed to have occurred on an object whose prototype is null, such as `Object.create(null)`.
I fixed this right away.

but, I don't have a clue about deserialize, can you provide a deserialized string? (or a bit of code you wrote....)

**Comment by elarrat** [comment]
I couldn't get to any code. I can get you the serialized string. Is pretty big though. Give me a couple of days and I'll bring it here

**Comment by elarrat** [comment]
https://drive.google.com/file/d/1-yyjzLaFxYSaAJxj6aAYh-jdtsrRwQhh/view?usp=share_link

**Comment by wan2land** [comment]
Found and fixed a bug in the escape string. Please try v0.3.4.

`AsyncFunction`, `AsyncGeneratorFunction`, and `Promise` don't work properly, please note when using them.
